// <auto-generated />
using System;
using KitapSatisSitesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitapSatisSitesi.Migrations
{
    [DbContext(typeof(KitapDbContext))]
    [Migration("20250729155944_SiparisKitapBackwardCompatibility")]
    partial class SiparisKitapBackwardCompatibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KitapSatisSitesi.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YayinYili")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YazarID")
                        .HasColumnType("INTEGER");

                    b.HasKey("KitapID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("YazarID");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Odeme", b =>
                {
                    b.Property<int>("OdemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiparisID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OdemeID");

                    b.HasIndex("SiparisID");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KitapID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SiparisID");

                    b.HasIndex("KitapID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.SiparisDetay", b =>
                {
                    b.Property<int>("SiparisDetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("KitapID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiparisID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SiparisDetayID");

                    b.HasIndex("KitapID");

                    b.HasIndex("SiparisID");

                    b.ToTable("SiparisDetaylar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Yazar", b =>
                {
                    b.Property<int>("YazarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("YazarID");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Yorum", b =>
                {
                    b.Property<int>("YorumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KitapID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("YorumID");

                    b.HasIndex("KitapID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Kitap", b =>
                {
                    b.HasOne("KitapSatisSitesi.Models.Kategori", "Kategori")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitapSatisSitesi.Models.Yazar", "Yazar")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YazarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Odeme", b =>
                {
                    b.HasOne("KitapSatisSitesi.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Siparis", b =>
                {
                    b.HasOne("KitapSatisSitesi.Models.Kitap", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapID");

                    b.HasOne("KitapSatisSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.SiparisDetay", b =>
                {
                    b.HasOne("KitapSatisSitesi.Models.Kitap", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitapSatisSitesi.Models.Siparis", "Siparis")
                        .WithMany("SiparisDetaylar")
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Yorum", b =>
                {
                    b.HasOne("KitapSatisSitesi.Models.Kitap", "Kitap")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KitapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitapSatisSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Kategori", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Kitap", b =>
                {
                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Kullanici", b =>
                {
                    b.Navigation("Siparisler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Siparis", b =>
                {
                    b.Navigation("SiparisDetaylar");
                });

            modelBuilder.Entity("KitapSatisSitesi.Models.Yazar", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
