CREATE TABLE Kullanici (
    KullaniciID INT PRIMARY KEY IDENTITY(1,1),
    Ad NVARCHAR(100) NOT NULL,
    Soyad NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    Parola NVARCHAR(100) NOT NULL
    Telefon NVARCHAR(15) NOT NULL
);

